# Generated by Django 6.0.6 on 2026-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
