# Generated by Django 6.0.4 on 2026-07-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('', 'Select Grade Level'), ('KG1', 'KG1'), ('KG2', 'KG2'), ('KG3', 'KG3'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5'), ('G6', 'Grade 6'), ('G7', 'Grade 7'), ('G8', 'Grade 8'), ('G9', 'Grade 9'), ('G10', 'Grade 10'), ('G11', 'Grade 11'), ('G12', 'Grade 12'), ('HL', 'Higher Level')], help_text='Applicable for students only', max_length=10, null=True),
        ),
    ]
