# Generated by Django 6.0.4 on 2026-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_grade_level_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv_document',
            field=models.FileField(blank=True, help_text='Applicable for teachers only (PDF, DOC, DOCX)', null=True, upload_to='cv_documents/'),
        ),
    ]
