# Generated by Django 6.0.4 on 2026-07-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_password_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialized_subject',
            field=models.CharField(blank=True, help_text='Applicable for teachers only — e.g. Mathematics, Physics, English', max_length=200, null=True),
        ),
    ]
