# Generated by Django 6.0.4 on 2026-08-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_specialized_subject_user_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specialized_subject',
        ),
    ]
