# Generated by Django 6.0.6 on 2026-07-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_teachersubject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
