# Generated by Django 6.0.4 on 2026-07-25 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.CharField(blank=True, help_text='Letter grade (A, B, C, D, F)', max_length=2),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
