# Generated by Django 6.0.4 on 2026-07-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
        ('subjects', '0005_add_grade_level_to_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbank',
            options={'ordering': ['-created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Question Bank'},
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after the question is answered'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. algebra, fractions', max_length=255),
        ),
        migrations.AlterField(
            model_name='questionbankchoice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
