GRADE_LEVEL_CHOICES = (
    ('', 'Select Grade Level'),
    ('KG1', 'KG1'),
    ('KG2', 'KG2'),
    ('KG3', 'KG3'),
    ('G1', 'Grade 1'),
    ('G2', 'Grade 2'),
    ('G3', 'Grade 3'),
    ('G4', 'Grade 4'),
    ('G5', 'Grade 5'),
    ('G6', 'Grade 6'),
    ('G7', 'Grade 7'),
    ('G8', 'Grade 8'),
    ('G9', 'Grade 9'),
    ('G10', 'Grade 10'),
    ('G11', 'Grade 11'),
    ('G12', 'Grade 12'),
    ('HL', 'Higher Level'),
)

